#ifndef	__libamtrs__java_classes__def__hpp
#define	__libamtrs__java_classes__def__hpp
#include "../inc/java/def.hpp"
#define	AMTRS_JAVA_CLASSES_NAMESPACE_BEGIN	AMTRS_JAVA_NAMESPACE_BEGIN namespace classes {
#define	AMTRS_JAVA_CLASSES_NAMESPACE_END	} AMTRS_JAVA_NAMESPACE_END
AMTRS_JAVA_CLASSES_NAMESPACE_BEGIN
AMTRS_JAVA_CLASSES_NAMESPACE_END
#endif
