/* Copyright (c) 2019, isaponsoft (Isao Shibuya) All rights reserved. *
 * Use of this source code is governed by a BSD-style  license that   *
 * can be found in the LICENSE file.                                  */
#ifndef	__libamtrs__android__java_classes__android__media__MediaPlayer__hpp
#define	__libamtrs__android__java_classes__android__media__MediaPlayer__hpp
AMTRS_JAVA_CLASSES_NAMESPACE_BEGIN
namespace android::content {
struct	Context;
}
namespace android::net {
struct	Uri;
}
namespace android::media {

AMTRS_JAVA_DEFINE_CLASS(MediaPlayer, java::lang::Object)
{
	using	Context	= android::content::Context;
	using	Uri		= android::net::Uri;

	AMTRS_JAVA_CLASS_SIGNATURE("android/media/MediaPlayer");


	// クラスメソッドとクラスフィールド
	AMTRS_JAVA_DEFINE_STATIC_MEMBER
	{
		AMTRS_JAVA_STATICS_BASIC;

		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_IO)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_MALFORMED)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_SERVER_DIED)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_TIMED_OUT)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_UNKNOWN)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_ERROR_UNSUPPORTED)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_BAD_INTERLEAVING)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_BUFFERING_END)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_BUFFERING_START)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_METADATA_UPDATE)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_NOT_SEEKABLE)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_STARTED_AS_NEXT)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_SUBTITLE_TIMED_OUT)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_UNKNOWN)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_UNSUPPORTED_SUBTITLE)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_VIDEO_RENDERING_START)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_INFO_VIDEO_TRACK_LAGGING)
		AMTRS_JAVA_DEFINE_FIELD(jint, MEDIA_MIMETYPE_TEXT_SUBRIP)
		AMTRS_JAVA_DEFINE_FIELD(jint, PREPARE_DRM_STATUS_PREPARATION_ERROR)
		AMTRS_JAVA_DEFINE_FIELD(jint, PREPARE_DRM_STATUS_PROVISIONING_NETWORK_ERROR)
		AMTRS_JAVA_DEFINE_FIELD(jint, PREPARE_DRM_STATUS_PROVISIONING_SERVER_ERROR)
		AMTRS_JAVA_DEFINE_FIELD(jint, PREPARE_DRM_STATUS_SUCCESS)
		AMTRS_JAVA_DEFINE_FIELD(jint, SEEK_CLOSEST)
		AMTRS_JAVA_DEFINE_FIELD(jint, SEEK_CLOSEST_SYNC)
		AMTRS_JAVA_DEFINE_FIELD(jint, SEEK_NEXT_SYNC)
		AMTRS_JAVA_DEFINE_FIELD(jint, SEEK_PREVIOUS_SYNC)
		AMTRS_JAVA_DEFINE_FIELD(jint, VIDEO_SCALING_MODE_SCALE_TO_FIT)
		AMTRS_JAVA_DEFINE_FIELD(jint, VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)


		AMTRS_JAVA_DEFINE_METHOD(create
			, MediaPlayer(Context context, Uri uri)
		)
	};


	// 動的メソッドと動的フィールド
	AMTRS_JAVA_DEFINE_DYNAMICS_MEMBER
	{
		AMTRS_JAVA_DYNAMICS_BASIC;

		AMTRS_JAVA_DEFINE_METHOD(start
			, void()
		)

		AMTRS_JAVA_DEFINE_METHOD(stop
			, void()
		)
	};
};


}
AMTRS_JAVA_CLASSES_NAMESPACE_END
#endif
