# example)
#		TARGET_NAME				"appmain"
# 		BUNDLE_IDENTIFIER		"org.myapp.app.product"
#		DISPLAY_NAME			"アプリ名"
#		VERSION_CODE			"1.2.3"
#		BUNDLE_VERSION			3
#		DEPLOYMENT_TARGET		11.0
#		RESOURCE_FILES			file(GLOB RESOURCE_FILES  "resources/*")
#		CODE_SIGN_IDENTITY		"iOS Developer"
#		DEVELOPMENT_TEAM		"A12B34C45"
#
#		TARGETED_DEVICE_FAMILY	"1,2"

set(CMAKE_CXX_FLAGS									"$(OTHER_CFLAGS) ${CMAKE_CXX_FLAGS} -x objective-c++")
set(CMAKE_OSX_DEPLOYMENT_TARGET						"${DEPLOYMENT_TARGET}" CACHE STRING "" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER	"com.klockworx.app.cafechantimer" CACHE STRING "" FORCE)
#set(CMAKE_USE_RELATIVE_PATHS						ON)

add_executable(
	${TARGET_NAME} MACOSX_BUNDLE
	${EVENT_PROGRAMS}
	${RESOURCE_FILES}			# 実行ファイルにリソースを追加
)

set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED		"NO")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY		${CODE_SIGN_IDENTITY})
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE			"NO" CACHE INTERNAL "")
set(CMAKE_XCODE_ATTRIBUTE_ARCHITECTURES				"$(ARVHS_STANDARD)" CACHE INTERNAL "")
set(CMAKE_XCODE_ATTRIBUTE_ARCHITECTURES				"$(ARVHS_STANDARD)" CACHE INTERNAL "")
#set(CMAKE_XCODE_ATTRIBUTE_SYMROOT					"" CACHE INTERNAL "")



set_target_properties(
	${TARGET_NAME}		PROPERTIES
	OUTPUT_NAME			ios
	MACOSX_BUNDLE_GUI_IDENTIFIER						${BUNDLE_IDENTIFIER}
	MACOSX_BUNDLE_DISPLAY_NAME							${DISPLAY_NAME}
	MACOSX_BUNDLE_LONG_VERSION_STRING					${VERSION_CODE}
	MACOSX_BUNDLE_SHORT_VERSION_STRING					${VERSION_CODE}
	MACOSX_BUNDLE_BUNDLE_VERSION						${BUNDLE_VERSION}

	# アイコン
	XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME	"AppIcon"

	CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY		${TARGETED_DEVICE_FAMILY}
	#MACOSX_FRAMEWORK_INFO_PLIST Info.plist
)


if (DEVELOPMENT_TEAM)
	set_target_properties(
		${TARGET_NAME}							PROPERTIES
#		XCODE_ATTRIBUTE_CODE_SIGN_STYLE			"Manual"
		XCODE_ATTRIBUTE_CODE_SIGN_STYLE			"Automatic"
		XCODE_ATTRIBUTE_DEVELOPMENT_TEAM		${DEVELOPMENT_TEAM}
	)
endif()

set_target_properties(
	${TARGET_NAME} PROPERTIES
	MACOSX_BUNDLE				TRUE
	RESOURCE					"${RESOURCE_FILES}"
)
