#ifndef	__libamtrs__node__hpp
#define	__libamtrs__node__hpp

#include "inc/node/node.hpp"
#ifndef	DEBUG
//#include "node/adbanner_node.hpp"
#endif
#include "inc/node/back_key_button_node.hpp"
#include "inc/node/back_key_node.hpp"
#include "inc/node/batch_sprite_node.hpp"
#include "inc/node/bitmap_font_node.hpp"
#include "inc/node/bitmap_numeric_node.hpp"
#include "inc/node/button_node.hpp"
#include "inc/node/button_sprite_node.hpp"
#include "inc/node/camera_node.hpp"
#include "inc/node/children_transform_node.hpp"
#include "inc/node/clipping_node.hpp"
#include "inc/node/color_button_node.hpp"
#include "inc/node/circle_node.hpp"
#include "inc/node/fill_node.hpp"
#include "inc/node/flickable_pager_node.hpp"
#include "inc/node/horizontal_pager_node.hpp"
#include "inc/node/input_untransparentable_node.hpp"
#include "inc/node/label_node.hpp"
#include "inc/node/list_node.hpp"
#include "inc/node/map_node.hpp"
#include "inc/node/movable_node.hpp"
#include "inc/node/overall_node.hpp"
#include "inc/node/pager_node.hpp"
#include "inc/node/pager_horizontal_node.hpp"
#include "inc/node/press_button_node.hpp"
#include "inc/node/scene_node.hpp"
#include "inc/node/scene_node_stack.hpp"
#include "inc/node/scroll_node.hpp"
#include "inc/node/sprite_node.hpp"
#include "inc/node/sprite_button_node.hpp"
#include "inc/node/string_node.hpp"
#include "inc/node/string_label_node.hpp"
#include "inc/node/subscene_node.hpp"
#include "inc/node/switch_node.hpp"
#include "inc/node/text_node.hpp"
#include "inc/node/virtualpad_node.hpp"
#include "inc/node/vertical_list_node.hpp"
#include "inc/node/vertical_pager_node.hpp"
#include "inc/node/window_frame_node.hpp"

#endif
