/* Copyright (c) 2019, isaponsoft (Isao Shibuya) All rights reserved. *
 * Use of this source code is governed by a BSD-style  license that   *
 * can be found in the LICENSE file.                                  */
#ifndef	__libamtrs__android__java_classes__android__Manifest__hpp
#define	__libamtrs__android__java_classes__android__Manifest__hpp
#include "../java/lang/String.hpp"
AMTRS_JAVA_CLASSES_NAMESPACE_BEGIN

namespace java::lang {
struct	String;
}


namespace android {


AMTRS_JAVA_DEFINE_CLASS(Manifest, java::lang::Object)
{
	AMTRS_JAVA_CLASS_SIGNATURE("android/Manifest");

	AMTRS_JAVA_DEFINE_CLASS(permission, java::lang::Object)
	{
		using	String		= java::lang::String;

		AMTRS_JAVA_CLASS_SIGNATURE("android/Manifest$permission");

		// クラスメソッドとクラスフィールド
		AMTRS_JAVA_DEFINE_STATIC_MEMBER
		{
			AMTRS_JAVA_STATICS_BASIC;

			AMTRS_JAVA_DEFINE_FIELD(String, ACCEPT_HANDOVER)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_BACKGROUND_LOCATION)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_CHECKIN_PROPERTIES)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_COARSE_LOCATION)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_FINE_LOCATION)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_LOCATION_EXTRA_COMMANDS)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_MEDIA_LOCATION)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_NETWORK_STATE)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_NOTIFICATION_POLICY)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCESS_WIFI_STATE)
			AMTRS_JAVA_DEFINE_FIELD(String, ACCOUNT_MANAGER)
			AMTRS_JAVA_DEFINE_FIELD(String, ACTIVITY_RECOGNITION)
			AMTRS_JAVA_DEFINE_FIELD(String, ADD_VOICEMAIL)
			AMTRS_JAVA_DEFINE_FIELD(String, ANSWER_PHONE_CALLS)
			AMTRS_JAVA_DEFINE_FIELD(String, BATTERY_STATS)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_ACCESSIBILITY_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_APPWIDGET)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_AUTOFILL_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CALL_REDIRECTION_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CARRIER_MESSAGING_CLIENT_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CARRIER_MESSAGING_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CARRIER_SERVICES)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CHOOSER_TARGET_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_CONDITION_PROVIDER_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_DEVICE_ADMIN)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_DREAM_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_INCALL_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_INPUT_METHOD)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_MIDI_DEVICE_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_NFC_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_NOTIFICATION_LISTENER_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_PRINT_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_QUICK_SETTINGS_TILE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_REMOTEVIEWS)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_SCREENING_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_TELECOM_CONNECTION_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_TEXT_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_TV_INPUT)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_VISUAL_VOICEMAIL_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_VOICE_INTERACTION)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_VPN_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_VR_LISTENER_SERVICE)
			AMTRS_JAVA_DEFINE_FIELD(String, BIND_WALLPAPER)
			AMTRS_JAVA_DEFINE_FIELD(String, BLUETOOTH)
			AMTRS_JAVA_DEFINE_FIELD(String, BLUETOOTH_ADMIN)
			AMTRS_JAVA_DEFINE_FIELD(String, BLUETOOTH_PRIVILEGED)
			AMTRS_JAVA_DEFINE_FIELD(String, BODY_SENSORS)
			AMTRS_JAVA_DEFINE_FIELD(String, BROADCAST_PACKAGE_REMOVED)
			AMTRS_JAVA_DEFINE_FIELD(String, BROADCAST_SMS)
			AMTRS_JAVA_DEFINE_FIELD(String, BROADCAST_STICKY)
			AMTRS_JAVA_DEFINE_FIELD(String, BROADCAST_WAP_PUSH)
			AMTRS_JAVA_DEFINE_FIELD(String, CALL_COMPANION_APP)
			AMTRS_JAVA_DEFINE_FIELD(String, CALL_PHONE)
			AMTRS_JAVA_DEFINE_FIELD(String, CALL_PRIVILEGED)
			AMTRS_JAVA_DEFINE_FIELD(String, CAMERA)
			AMTRS_JAVA_DEFINE_FIELD(String, CAPTURE_AUDIO_OUTPUT)
			AMTRS_JAVA_DEFINE_FIELD(String, CHANGE_COMPONENT_ENABLED_STATE)

			AMTRS_JAVA_DEFINE_FIELD(String, READ_CALENDAR)
			AMTRS_JAVA_DEFINE_FIELD(String, READ_EXTERNAL_STORAGE)
			AMTRS_JAVA_DEFINE_FIELD(String, WRITE_CALENDAR)
			AMTRS_JAVA_DEFINE_FIELD(String, WRITE_EXTERNAL_STORAGE)

		};


		// 動的メソッドと動的フィールド
		AMTRS_JAVA_DEFINE_DYNAMICS_MEMBER
		{
			AMTRS_JAVA_DYNAMICS_BASIC;
		};
	};
};

}
AMTRS_JAVA_CLASSES_NAMESPACE_END
#endif
