/* Copyright (c) 2019, isaponsoft (Isao Shibuya) All rights reserved. *
 * Use of this source code is governed by a BSD-style  license that   *
 * can be found in the LICENSE file.                                  */
#ifndef	__libamtrs__android__java_classes__android_view_WindowManager__hpp
#define	__libamtrs__android__java_classes__android_view_WindowManager__hpp
#include "ViewGroup.hpp"
#include "ViewManager.hpp"
AMTRS_JAVA_CLASSES_NAMESPACE_BEGIN

namespace android::view {

struct	Display;


// https://developer.android.com/reference/android/view/WindowManager
AMTRS_JAVA_DEFINE_CLASS(WindowManager, ViewManager)
{
	AMTRS_JAVA_CLASS_SIGNATURE("android/view/WindowManager");


	// クラスメソッドとクラスフィールド
	AMTRS_JAVA_DEFINE_STATIC_MEMBER
	{
		AMTRS_JAVA_STATICS_BASIC;
	};


	// 動的メソッドと動的フィールド
	AMTRS_JAVA_DEFINE_DYNAMICS_MEMBER
	{
		AMTRS_JAVA_DYNAMICS_BASIC;


		AMTRS_JAVA_DEFINE_METHOD(getDefaultDisplay
			, Display()
		)
	};



	AMTRS_JAVA_DEFINE_CLASS(LayoutParams, android::view::ViewGroup::LayoutParams)
	{
		AMTRS_JAVA_CLASS_SIGNATURE("android/view/WindowManager$LayoutParams");

		// クラスメソッドとクラスフィールド
		AMTRS_JAVA_DEFINE_STATIC_MEMBER
		{
			AMTRS_JAVA_STATICS_BASIC;

			AMTRS_JAVA_DEFINE_FIELD(jint, ALPHA_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, ANIMATION_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jfloat, BRIGHTNESS_OVERRIDE_FULL)
			AMTRS_JAVA_DEFINE_FIELD(jfloat, BRIGHTNESS_OVERRIDE_NONE)
			AMTRS_JAVA_DEFINE_FIELD(jfloat, BRIGHTNESS_OVERRIDE_OFF)
			AMTRS_JAVA_DEFINE_FIELD(jint, DIM_AMOUNT_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, FIRST_APPLICATION_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, FIRST_SUB_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, FIRST_SYSTEM_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAGS_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_ALLOW_LOCK_WHILE_SCREEN_ON)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_ALT_FOCUSABLE_IM)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_BLUR_BEHIND)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_DIM_BEHIND)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_DISMISS_KEYGUARD)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_DITHER)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_FORCE_NOT_FULLSCREEN)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_FULLSCREEN)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_HARDWARE_ACCELERATED)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_IGNORE_CHEEK_PRESSES)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_KEEP_SCREEN_ON)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LAYOUT_ATTACHED_IN_DECOR)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LAYOUT_INSET_DECOR)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LAYOUT_IN_OVERSCAN)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LAYOUT_IN_SCREEN)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LAYOUT_NO_LIMITS)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_LOCAL_FOCUS_MODE)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_NOT_FOCUSABLE)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_NOT_TOUCHABLE)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_NOT_TOUCH_MODAL)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_SCALED)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_SECURE)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_SHOW_WALLPAPER)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_SHOW_WHEN_LOCKED)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_SPLIT_TOUCH)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_TOUCHABLE_WHEN_WAKING)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_TRANSLUCENT_NAVIGATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_TRANSLUCENT_STATUS)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_TURN_SCREEN_ON)
			AMTRS_JAVA_DEFINE_FIELD(jint, FLAG_WATCH_OUTSIDE_TOUCH)
			AMTRS_JAVA_DEFINE_FIELD(jint, FORMAT_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAST_APPLICATION_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAST_SUB_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAST_SYSTEM_WINDOW)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAYOUT_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER)
			AMTRS_JAVA_DEFINE_FIELD(jint, LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES)
			AMTRS_JAVA_DEFINE_FIELD(jint, MEMORY_TYPE_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, MEMORY_TYPE_GPU)
			AMTRS_JAVA_DEFINE_FIELD(jint, MEMORY_TYPE_HARDWARE)
			AMTRS_JAVA_DEFINE_FIELD(jint, MEMORY_TYPE_NORMAL)
			AMTRS_JAVA_DEFINE_FIELD(jint, MEMORY_TYPE_PUSH_BUFFERS)
			AMTRS_JAVA_DEFINE_FIELD(jint, ROTATION_ANIMATION_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, ROTATION_ANIMATION_CROSSFADE)
			AMTRS_JAVA_DEFINE_FIELD(jint, ROTATION_ANIMATION_JUMPCUT)
			AMTRS_JAVA_DEFINE_FIELD(jint, ROTATION_ANIMATION_ROTATE)
			AMTRS_JAVA_DEFINE_FIELD(jint, ROTATION_ANIMATION_SEAMLESS)
			AMTRS_JAVA_DEFINE_FIELD(jint, SCREEN_BRIGHTNESS_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SCREEN_ORIENTATION_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_ADJUST_NOTHING)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_ADJUST_PAN)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_ADJUST_RESIZE)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_ADJUST_UNSPECIFIED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_IS_FORWARD_NAVIGATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_MASK_ADJUST)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_MASK_STATE)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_MODE_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_ALWAYS_HIDDEN)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_ALWAYS_VISIBLE)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_HIDDEN)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_UNCHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_UNSPECIFIED)
			AMTRS_JAVA_DEFINE_FIELD(jint, SOFT_INPUT_STATE_VISIBLE)
			AMTRS_JAVA_DEFINE_FIELD(jint, TITLE_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_ACCESSIBILITY_OVERLAY)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_ATTACHED_DIALOG)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_MEDIA)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_OVERLAY)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_PANEL)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_STARTING)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_APPLICATION_SUB_PANEL)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_BASE_APPLICATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_CHANGED)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_DRAWN_APPLICATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_INPUT_METHOD)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_INPUT_METHOD_DIALOG)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_KEYGUARD_DIALOG)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_PHONE)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_PRIORITY_PHONE)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_PRIVATE_PRESENTATION)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_SEARCH_BAR)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_STATUS_BAR)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_STATUS_BAR_PANEL)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_SYSTEM_ALERT)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_SYSTEM_DIALOG)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_SYSTEM_ERROR)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_SYSTEM_OVERLAY)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_TOAST)
			AMTRS_JAVA_DEFINE_FIELD(jint, TYPE_WALLPAPER)
		};

		// 動的メソッドと動的フィールド
		AMTRS_JAVA_DEFINE_DYNAMICS_MEMBER
		{
			AMTRS_JAVA_DYNAMICS_BASIC;
		};
	};
};


}
AMTRS_JAVA_CLASSES_NAMESPACE_END
#endif
