/* Copyright (c) 2019, isaponsoft (Isao Shibuya) All rights reserved. *
 * Use of this source code is governed by a BSD-style  license that   *
 * can be found in the LICENSE file.                                  */
__AMTRS__VULKAN_FUNC(vkCreateInstance)
__AMTRS__VULKAN_FUNC(vkDestroyInstance)
__AMTRS__VULKAN_FUNC(vkEnumeratePhysicalDevices)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceFeatures)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceFormatProperties)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceImageFormatProperties)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceProperties)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceQueueFamilyProperties)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceMemoryProperties)
__AMTRS__VULKAN_FUNC(vkGetInstanceProcAddr)
__AMTRS__VULKAN_FUNC(vkGetDeviceProcAddr)
__AMTRS__VULKAN_FUNC(vkCreateDevice)
__AMTRS__VULKAN_FUNC(vkDestroyDevice)
__AMTRS__VULKAN_FUNC(vkEnumerateInstanceExtensionProperties)
__AMTRS__VULKAN_FUNC(vkEnumerateDeviceExtensionProperties)
__AMTRS__VULKAN_FUNC(vkEnumerateInstanceLayerProperties)
__AMTRS__VULKAN_FUNC(vkEnumerateDeviceLayerProperties)
__AMTRS__VULKAN_FUNC(vkGetDeviceQueue)
__AMTRS__VULKAN_FUNC(vkQueueSubmit)
__AMTRS__VULKAN_FUNC(vkQueueWaitIdle)
__AMTRS__VULKAN_FUNC(vkDeviceWaitIdle)
__AMTRS__VULKAN_FUNC(vkAllocateMemory)
__AMTRS__VULKAN_FUNC(vkFreeMemory)
__AMTRS__VULKAN_FUNC(vkMapMemory)
__AMTRS__VULKAN_FUNC(vkUnmapMemory)
__AMTRS__VULKAN_FUNC(vkFlushMappedMemoryRanges)
__AMTRS__VULKAN_FUNC(vkInvalidateMappedMemoryRanges)
__AMTRS__VULKAN_FUNC(vkGetDeviceMemoryCommitment)
__AMTRS__VULKAN_FUNC(vkBindBufferMemory)
__AMTRS__VULKAN_FUNC(vkBindImageMemory)
__AMTRS__VULKAN_FUNC(vkGetBufferMemoryRequirements)
__AMTRS__VULKAN_FUNC(vkGetImageMemoryRequirements)
__AMTRS__VULKAN_FUNC(vkGetImageSparseMemoryRequirements)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceSparseImageFormatProperties)
__AMTRS__VULKAN_FUNC(vkQueueBindSparse)
__AMTRS__VULKAN_FUNC(vkCreateFence)
__AMTRS__VULKAN_FUNC(vkDestroyFence)
__AMTRS__VULKAN_FUNC(vkResetFences)
__AMTRS__VULKAN_FUNC(vkGetFenceStatus)
__AMTRS__VULKAN_FUNC(vkWaitForFences)
__AMTRS__VULKAN_FUNC(vkCreateSemaphore)
__AMTRS__VULKAN_FUNC(vkDestroySemaphore)
__AMTRS__VULKAN_FUNC(vkCreateEvent)
__AMTRS__VULKAN_FUNC(vkDestroyEvent)
__AMTRS__VULKAN_FUNC(vkGetEventStatus)
__AMTRS__VULKAN_FUNC(vkSetEvent)
__AMTRS__VULKAN_FUNC(vkResetEvent)
__AMTRS__VULKAN_FUNC(vkCreateQueryPool)
__AMTRS__VULKAN_FUNC(vkDestroyQueryPool)
__AMTRS__VULKAN_FUNC(vkGetQueryPoolResults)
__AMTRS__VULKAN_FUNC(vkCreateBuffer)
__AMTRS__VULKAN_FUNC(vkDestroyBuffer)
__AMTRS__VULKAN_FUNC(vkCreateBufferView)
__AMTRS__VULKAN_FUNC(vkDestroyBufferView)
__AMTRS__VULKAN_FUNC(vkCreateImage)
__AMTRS__VULKAN_FUNC(vkDestroyImage)
__AMTRS__VULKAN_FUNC(vkGetImageSubresourceLayout)
__AMTRS__VULKAN_FUNC(vkCreateImageView)
__AMTRS__VULKAN_FUNC(vkDestroyImageView)
__AMTRS__VULKAN_FUNC(vkCreateShaderModule)
__AMTRS__VULKAN_FUNC(vkDestroyShaderModule)
__AMTRS__VULKAN_FUNC(vkCreatePipelineCache)
__AMTRS__VULKAN_FUNC(vkDestroyPipelineCache)
__AMTRS__VULKAN_FUNC(vkGetPipelineCacheData)
__AMTRS__VULKAN_FUNC(vkMergePipelineCaches)
__AMTRS__VULKAN_FUNC(vkCreateGraphicsPipelines)
__AMTRS__VULKAN_FUNC(vkCreateComputePipelines)
__AMTRS__VULKAN_FUNC(vkDestroyPipeline)
__AMTRS__VULKAN_FUNC(vkCreatePipelineLayout)
__AMTRS__VULKAN_FUNC(vkDestroyPipelineLayout)
__AMTRS__VULKAN_FUNC(vkCreateSampler)
__AMTRS__VULKAN_FUNC(vkDestroySampler)
__AMTRS__VULKAN_FUNC(vkCreateDescriptorSetLayout)
__AMTRS__VULKAN_FUNC(vkDestroyDescriptorSetLayout)
__AMTRS__VULKAN_FUNC(vkCreateDescriptorPool)
__AMTRS__VULKAN_FUNC(vkDestroyDescriptorPool)
__AMTRS__VULKAN_FUNC(vkResetDescriptorPool)
__AMTRS__VULKAN_FUNC(vkAllocateDescriptorSets)
__AMTRS__VULKAN_FUNC(vkFreeDescriptorSets)
__AMTRS__VULKAN_FUNC(vkUpdateDescriptorSets)
__AMTRS__VULKAN_FUNC(vkCreateFramebuffer)
__AMTRS__VULKAN_FUNC(vkDestroyFramebuffer)
__AMTRS__VULKAN_FUNC(vkCreateRenderPass)
__AMTRS__VULKAN_FUNC(vkDestroyRenderPass)
__AMTRS__VULKAN_FUNC(vkGetRenderAreaGranularity)
__AMTRS__VULKAN_FUNC(vkCreateCommandPool)
__AMTRS__VULKAN_FUNC(vkDestroyCommandPool)
__AMTRS__VULKAN_FUNC(vkResetCommandPool)
__AMTRS__VULKAN_FUNC(vkAllocateCommandBuffers)
__AMTRS__VULKAN_FUNC(vkFreeCommandBuffers)
__AMTRS__VULKAN_FUNC(vkBeginCommandBuffer)
__AMTRS__VULKAN_FUNC(vkEndCommandBuffer)
__AMTRS__VULKAN_FUNC(vkResetCommandBuffer)
__AMTRS__VULKAN_FUNC(vkCmdBindPipeline)
__AMTRS__VULKAN_FUNC(vkCmdSetViewport)
__AMTRS__VULKAN_FUNC(vkCmdSetScissor)
__AMTRS__VULKAN_FUNC(vkCmdSetLineWidth)
__AMTRS__VULKAN_FUNC(vkCmdSetDepthBias)
__AMTRS__VULKAN_FUNC(vkCmdSetBlendConstants)
__AMTRS__VULKAN_FUNC(vkCmdSetDepthBounds)
__AMTRS__VULKAN_FUNC(vkCmdSetStencilCompareMask)
__AMTRS__VULKAN_FUNC(vkCmdSetStencilWriteMask)
__AMTRS__VULKAN_FUNC(vkCmdSetStencilReference)
__AMTRS__VULKAN_FUNC(vkCmdBindDescriptorSets)
__AMTRS__VULKAN_FUNC(vkCmdBindIndexBuffer)
__AMTRS__VULKAN_FUNC(vkCmdBindVertexBuffers)
__AMTRS__VULKAN_FUNC(vkCmdDraw)
__AMTRS__VULKAN_FUNC(vkCmdDrawIndexed)
__AMTRS__VULKAN_FUNC(vkCmdDrawIndirect)
__AMTRS__VULKAN_FUNC(vkCmdDrawIndexedIndirect)
__AMTRS__VULKAN_FUNC(vkCmdDispatch)
__AMTRS__VULKAN_FUNC(vkCmdDispatchIndirect)
__AMTRS__VULKAN_FUNC(vkCmdCopyBuffer)
__AMTRS__VULKAN_FUNC(vkCmdCopyImage)
__AMTRS__VULKAN_FUNC(vkCmdBlitImage)
__AMTRS__VULKAN_FUNC(vkCmdCopyBufferToImage)
__AMTRS__VULKAN_FUNC(vkCmdCopyImageToBuffer)
__AMTRS__VULKAN_FUNC(vkCmdUpdateBuffer)
__AMTRS__VULKAN_FUNC(vkCmdFillBuffer)
__AMTRS__VULKAN_FUNC(vkCmdClearColorImage)
__AMTRS__VULKAN_FUNC(vkCmdClearDepthStencilImage)
__AMTRS__VULKAN_FUNC(vkCmdClearAttachments)
__AMTRS__VULKAN_FUNC(vkCmdResolveImage)
__AMTRS__VULKAN_FUNC(vkCmdSetEvent)
__AMTRS__VULKAN_FUNC(vkCmdResetEvent)
__AMTRS__VULKAN_FUNC(vkCmdWaitEvents)
__AMTRS__VULKAN_FUNC(vkCmdPipelineBarrier)
__AMTRS__VULKAN_FUNC(vkCmdBeginQuery)
__AMTRS__VULKAN_FUNC(vkCmdEndQuery)
__AMTRS__VULKAN_FUNC(vkCmdResetQueryPool)
__AMTRS__VULKAN_FUNC(vkCmdWriteTimestamp)
__AMTRS__VULKAN_FUNC(vkCmdCopyQueryPoolResults)
__AMTRS__VULKAN_FUNC(vkCmdPushConstants)
__AMTRS__VULKAN_FUNC(vkCmdBeginRenderPass)
__AMTRS__VULKAN_FUNC(vkCmdNextSubpass)
__AMTRS__VULKAN_FUNC(vkCmdEndRenderPass)
__AMTRS__VULKAN_FUNC(vkCmdExecuteCommands)

// VK_KHR_surface
__AMTRS__VULKAN_FUNC(vkDestroySurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceSurfaceSupportKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceSurfaceFormatsKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceSurfacePresentModesKHR)

// VK_KHR_swapchain
__AMTRS__VULKAN_FUNC(vkCreateSwapchainKHR)
__AMTRS__VULKAN_FUNC(vkDestroySwapchainKHR)
__AMTRS__VULKAN_FUNC(vkGetSwapchainImagesKHR)
__AMTRS__VULKAN_FUNC(vkAcquireNextImageKHR)
__AMTRS__VULKAN_FUNC(vkQueuePresentKHR)

// VK_KHR_display
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceDisplayPropertiesKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceDisplayPlanePropertiesKHR)
__AMTRS__VULKAN_FUNC(vkGetDisplayPlaneSupportedDisplaysKHR)
__AMTRS__VULKAN_FUNC(vkGetDisplayModePropertiesKHR)
__AMTRS__VULKAN_FUNC(vkCreateDisplayModeKHR)
__AMTRS__VULKAN_FUNC(vkGetDisplayPlaneCapabilitiesKHR)
__AMTRS__VULKAN_FUNC(vkCreateDisplayPlaneSurfaceKHR)

// VK_KHR_display_swapchain
__AMTRS__VULKAN_FUNC(vkCreateSharedSwapchainsKHR)

// VK_KHR_xlib_surface
#ifdef	VK_USE_PLATFORM_XLIB_KHR
__AMTRS__VULKAN_FUNC(vkCreateXlibSurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceXlibPresentationSupportKHR)
#endif

// VK_KHR_xcb_surface
#ifdef	VK_USE_PLATFORM_XCB_KHR
__AMTRS__VULKAN_FUNC(vkCreateXcbSurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceXcbPresentationSupportKHR)
#endif

// VK_KHR_wayland_surface
#ifdef	VK_USE_PLATFORM_WAYLAND_KHR
__AMTRS__VULKAN_FUNC(vkCreateWaylandSurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceWaylandPresentationSupportKHR)
#endif

// VK_KHR_mir_surface
#ifdef	VK_USE_PLATFORM_MIR_KHR
__AMTRS__VULKAN_FUNC(vkCreateMirSurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceMirPresentationSupportKHR)
#endif

// VK_KHR_android_surface
#ifdef	VK_USE_PLATFORM_ANDROID_KHR
__AMTRS__VULKAN_FUNC(vkCreateAndroidSurfaceKHR)
#endif

// VK_KHR_win32_surface
#ifdef	VK_USE_PLATFORM_WIN32_KHR
__AMTRS__VULKAN_FUNC(vkCreateWin32SurfaceKHR)
__AMTRS__VULKAN_FUNC(vkGetPhysicalDeviceWin32PresentationSupportKHR)
#endif
